// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNziTimlIvhsvd4DPVcNaSl-UqEwQ1MF8',
    appId: '1:885905678676:web:e924d6157bc9fdc855e8c1',
    messagingSenderId: '885905678676',
    projectId: 'livraria-14eb4',
    authDomain: 'livraria-14eb4.firebaseapp.com',
    storageBucket: 'livraria-14eb4.firebasestorage.app',
    measurementId: 'G-QC7XJKS0KF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAohl-PL0T1pD9DPHq9EUDl0ySqdSKzjk',
    appId: '1:885905678676:android:50dc82d5eec71dae55e8c1',
    messagingSenderId: '885905678676',
    projectId: 'livraria-14eb4',
    storageBucket: 'livraria-14eb4.firebasestorage.app',
  );
}
